
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 25 20:37:00 CST 2017
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 11;
  public static final int IDENT = 28;
  public static final int SEMICOLON = 26;
  public static final int ELSE = 19;
  public static final int PLUS = 2;
  public static final int RBRACE = 25;
  public static final int RPAREN = 23;
  public static final int OR = 12;
  public static final int INT = 16;
  public static final int EQUAL = 9;
  public static final int WHILE = 20;
  public static final int GREATER = 7;
  public static final int IF = 18;
  public static final int LBRACE = 24;
  public static final int LPAREN = 22;
  public static final int QUOTE = 17;
  public static final int NUMBER = 27;
  public static final int EOF = 0;
  public static final int UNEQUAL = 10;
  public static final int MAIN = 13;
  public static final int BREAK = 21;
  public static final int DIV = 5;
  public static final int PUTW = 14;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int PUTS = 15;
  public static final int ASSIGN = 6;
  public static final int MUL = 4;
  public static final int LESS = 8;
}

